#!/bin/bash

TIMES=$1;

for ((i=1;i<=$TIMES;i++))
do
	echo "/etc/snmposter/agents/Var$i.snmpwalk,127.0.1.$i" >> /etc/snmposter/agents.csv
	snmpwalk -On -v2c -c dpa 127.0.1.$i 1 > /etc/snmposter/agents/Var$i.snmpwalk
done